//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteRestful.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.OrdemServico = new HashSet<OrdemServico>();
        }
    
        public string IdCliente { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string Celular { get; set; }
        public string TelRes { get; set; }

        [IgnoreDataMember]
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
    }
}
