//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteRestful.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class ServicoPorOS
    {
        public int IdSPO { get; set; }
        public int IdOS { get; set; }
        public int IdServico { get; set; }
        public string Numero { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }

        [IgnoreDataMember]
        public virtual OrdemServico OrdemServico { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
